# **Lab 2 Tasks**


**Task 1: Vectors**

•	Create a vector containing the ages of 6 people of your choice.

•	Print the vector's shape, dimensions, and data type.

•	Create a second vector of the same size representing "years until retirement" (65 − age) without using a loop.

•	Find and print the average age using a NumPy function (do not calculate it manually).

In [24]:
import numpy as np

ages = np.array([18, 25, 32, 45, 50, 61])
print("===Ages Vector===\n", ages)

print("\n===Vector Information===")
print("Shape:", ages.shape)
print("Dimensions:", ages.ndim)
print("Data Type:", ages.dtype)

years_to_retirement = 65 - ages
print("\n===Years to Retirement===\n", years_to_retirement)

average_age = np.mean(ages)
print("\n===Average Age===")
print("Average Age:", average_age)

===Ages Vector===
 [18 25 32 45 50 61]

===Vector Information===
Shape: (6,)
Dimensions: 1
Data Type: int64

===Years to Retirement===
 [47 40 33 20 15  4]

===Average Age===
Average Age: 38.5


**Task 2: Matrices**

•	Create a 4×3 matrix representing the sales (in units) of 4 products across 3 months.

•	Print the matrix's shape and total number of elements.

•	Create a second matrix of the same shape filled entirely with zeros using a NumPy function (not by typing zeros manually).

•	Replace the zero matrix's second row with the values [10, 20, 30] using indexing (not by recreating the matrix).

In [25]:
import numpy as np

sales = np.array([
    [12, 15, 20],
    [8, 10, 14],
    [25, 30, 22],
    [5, 9, 11]
])
print("===Sales Matrix===\n", sales)

print("\n===Matrix Info===")
print("Shape:", sales.shape)
print("Total Elements:", sales.size)

zeros_matrix = np.zeros(sales.shape, dtype=int)
print("\n===Initial Zeros Matrix===\n", zeros_matrix)

zeros_matrix[1] = [10, 20, 30]

print("\n===Updated Zeros Matrix===\n", zeros_matrix)

===Sales Matrix===
 [[12 15 20]
 [ 8 10 14]
 [25 30 22]
 [ 5  9 11]]

===Matrix Info===
Shape: (4, 3)
Total Elements: 12

===Initial Zeros Matrix===
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

===Updated Zeros Matrix===
 [[ 0  0  0]
 [10 20 30]
 [ 0  0  0]
 [ 0  0  0]]


**Task 3: Addition & Subtraction**

•	Create two 3×3 matrices representing the marks of 3 students in 3 subjects for Term 1 and Term 2.

•	Calculate the total combined marks (Term 1 + Term 2) for each student in each subject.

•	Calculate the improvement (Term 2 − Term 1) for each student in each subject.

•	Using the improvement matrix, identify (through code, not by manually reading) which student had the highest total improvement across all subjects.

In [26]:
import numpy as np

term1 = np.array([
    [75, 80, 85],
    [90, 85, 88],
    [60, 70, 65]
])

term2 = np.array([
    [80, 82, 89],
    [88, 87, 92],
    [75, 80, 85]
])

print("=== Term 1 Marks ===\n", term1)
print("\n=== Term 2 Marks ===\n", term2)

total_marks = term1 + term2
print("\n=== Total Combined Marks ===\n", total_marks)

improvement = term2 - term1
print("\n=== Improvement ===\n", improvement)

student_improvements = np.sum(improvement, axis=1)
best_student_index = np.argmax(student_improvements)

print("\n=== Total Improvement Per Student ===")
for i, imp in enumerate(student_improvements):
    print(f"Student {i+1}: {imp} marks")

print(f"\nStudent with the highest total improvement: Student {best_student_index + 1}")

=== Term 1 Marks ===
 [[75 80 85]
 [90 85 88]
 [60 70 65]]

=== Term 2 Marks ===
 [[80 82 89]
 [88 87 92]
 [75 80 85]]

=== Total Combined Marks ===
 [[155 162 174]
 [178 172 180]
 [135 150 150]]

=== Improvement ===
 [[ 5  2  4]
 [-2  2  4]
 [15 10 20]]

=== Total Improvement Per Student ===
Student 1: 11 marks
Student 2: 4 marks
Student 3: 45 marks

Student with the highest total improvement: Student 3


**Task 4: Dot Product**

•	Create a vector of 4 item prices and a vector of the quantities purchased for each item.

•	Calculate the total bill using the dot product (not by multiplying and adding manually).

•	Create a 2×4 matrix representing quantities purchased by 2 different customers, then calculate the total bill for both customers using a single dot product operation.

•	Explain (in a comment in your code) why the shapes of the two arrays had to match a specific way for the dot product to work.

In [27]:
import numpy as np

prices = np.array([10, 20, 5, 50])
quantities = np.array([3, 1, 10, 2])

print("Prices:", prices)
print("Quantities:", quantities)

total_bill = np.dot(prices, quantities)
print("Total bill (single customer):", total_bill)

customer_quantities = np.array([
    [3, 1, 10, 2],
    [1, 5, 2, 4]
])

customer_bills = np.dot(customer_quantities, prices)
print("\nCustomer Quantities Matrix:\n", customer_quantities)
print("Total bills for both customers:", customer_bills)

Prices: [10 20  5 50]
Quantities: [ 3  1 10  2]
Total bill (single customer): 200

Customer Quantities Matrix:
 [[ 3  1 10  2]
 [ 1  5  2  4]]
Total bills for both customers: [200 320]


**Task 5: Reshaping**

•	Create a 1D array of 12 numbers representing hours studied by a student over 12 days.

•	Reshape this array into a 3×4 matrix (3 weeks... wait, adjust: 4 rows × 3 days) representing 4 weeks of a 3-day study plan.

•	Reshape the same original array into a different valid shape (not 4×3), and print both reshaped versions.

•	Try reshaping the array into a shape that is not possible (e.g., 5×3) and note down the error message you get.

In [28]:
import numpy as np

hours = np.array([2, 3, 1, 4, 0, 5, 2, 6, 1, 3, 2, 4])
print("Original 1D Array:", hours)

weeks_4_days_3 = hours.reshape(4, 3)
print("\nReshaped to 4x3 (4 weeks, 3 study days per week):\n", weeks_4_days_3)

weeks_3_days_4 = hours.reshape(3, 4)
print("\nReshaped to 3x4 (different valid shape):\n", weeks_3_days_4)

try:
    impossible_shape = hours.reshape(5, 3)
except ValueError as e:
    print("\n--- Attempted Impossible Reshape (5x3) ---")
    print("Error Message:", e)

Original 1D Array: [2 3 1 4 0 5 2 6 1 3 2 4]

Reshaped to 4x3 (4 weeks, 3 study days per week):
 [[2 3 1]
 [4 0 5]
 [2 6 1]
 [3 2 4]]

Reshaped to 3x4 (different valid shape):
 [[2 3 1 4]
 [0 5 2 6]
 [1 3 2 4]]

--- Attempted Impossible Reshape (5x3) ---
Error Message: cannot reshape array of size 12 into shape (5,3)


**Task 6: Indexing**

•	Create a 5×5 matrix filled with random integers between 1 and 50.

•	Access and print the element in the 3rd row and 4th column using indexing.

•	Access and print the last row and the last column using negative indexing.

•	Change the value of the element at position (0,0) to 999 using indexing, then print the updated matrix.

In [29]:
import numpy as np

np.random.seed(42)
matrix = np.random.randint(1, 51, size=(5, 5))
print("=== Original 5x5 Matrix ===\n", matrix)

element_3_4 = matrix[2, 3]
print(f"\nElement at 3rd row, 4th column (index [2,3]): {element_3_4}")

last_row = matrix[-1, :]
last_column = matrix[:, -1]
print("\nLast row (negative indexing):", last_row)
print("Last column (negative indexing):", last_column)

matrix[0, 0] = 999
print("\n=== Updated Matrix (position 0,0 changed to 999) ===\n", matrix)

=== Original 5x5 Matrix ===
 [[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]

Element at 3rd row, 4th column (index [2,3]): 40

Last row (negative indexing): [30 38  2 21 33]
Last column (negative indexing): [ 8 11 24 44 33]

=== Updated Matrix (position 0,0 changed to 999) ===
 [[999  29  15  43   8]
 [ 21  39  19  23  11]
 [ 11  24  36  40  24]
 [  3  22   2  24  44]
 [ 30  38   2  21  33]]


**Task 7: Slicing**

•	Create a 6×6 matrix filled with numbers from 1 to 36 (in order).

•	Extract the top-left 3×3 sub-matrix using slicing.

•	Extract every alternate row and every alternate column from the full matrix using step slicing.

•	Extract the last 2 rows and last 2 columns together as a single sub-matrix.

In [30]:
import numpy as np

matrix_6x6 = np.arange(1, 37).reshape(6, 6)
print("=== Original 6x6 Matrix ===\n", matrix_6x6)

top_left_3x3 = matrix_6x6[0:3, 0:3]
print("\n=== Top-Left 3x3 Sub-Matrix ===\n", top_left_3x3)

alternating = matrix_6x6[::2, ::2]
print("\n=== Every Alternate Row & Column ===\n", alternating)

last_2x2 = matrix_6x6[-2:, -2:]
print("\n=== Last 2 Rows & 2 Columns ===\n", last_2x2)

=== Original 6x6 Matrix ===
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

=== Top-Left 3x3 Sub-Matrix ===
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

=== Every Alternate Row & Column ===
 [[ 1  3  5]
 [13 15 17]
 [25 27 29]]

=== Last 2 Rows & 2 Columns ===
 [[29 30]
 [35 36]]


**Task 8: Random Matrices**

•	Set a random seed of your choice, then generate a 3×3 matrix of random decimal values between 0 and 1.

•	Generate a 3×3 matrix of random integers between 10 and 100.

•	Generate a 4×4 matrix using the standard normal distribution (values can be negative).

•	Without changing the seed, run your random decimal generation code (part 1) twice and compare, explain in a comment why both outputs are identical.

In [31]:
import numpy as np

np.random.seed(42)
decimal_matrix_1 = np.random.rand(3, 3)
print("=== Random Decimals (First Run) ===\n", decimal_matrix_1)

random_ints = np.random.randint(10, 101, size=(3, 3))
print("\n=== Random Integers (10 to 100) ===\n", random_ints)

normal_matrix = np.random.randn(4, 4)
print("\n=== Standard Normal Matrix ===\n", normal_matrix)

decimal_matrix_no_reset = np.random.rand(3, 3)

np.random.seed(42)
decimal_matrix_with_reset = np.random.rand(3, 3)

print("\n=== Random Decimals (Second Run, without resetting seed) ===\n", decimal_matrix_no_reset)
print("\n=== Random Decimals (Third Run, AFTER resetting seed back to 42) ===\n", decimal_matrix_with_reset)

=== Random Decimals (First Run) ===
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

=== Random Integers (10 to 100) ===
 [[33 12 31]
 [62 11 97]
 [39 47 11]]

=== Standard Normal Matrix ===
 [[-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877 -0.2257763 ]
 [ 0.0675282  -1.42474819 -0.54438272  0.11092259]]

=== Random Decimals (Second Run, without resetting seed) ===
 [[0.60754485 0.17052412 0.06505159]
 [0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303]]

=== Random Decimals (Third Run, AFTER resetting seed back to 42) ===
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


**Task 9: Transpose**

•	Create a 3×5 matrix representing 3 employees' performance scores across 5 months.

•	Transpose the matrix and print its new shape.
•	Verify programmatically (using code, not by manual inspection) that transposing the matrix twice gives back the original matrix.

•	Create a 4×2 and a 3×2 matrix, and use transpose on one of them so that a dot product between the two becomes possible; then perform the dot product.

In [32]:
import numpy as np

scores = np.array([
    [85, 90, 88, 92, 95],
    [70, 75, 80, 78, 85],
    [95, 98, 92, 90, 89]
])
print("=== Original Scores Matrix (3x5) ===\n", scores)

scores_transposed = scores.T
print("\n=== Transposed Scores Matrix (5x3) ===\n", scores_transposed)
print("New Shape:", scores_transposed.shape)

double_transpose = scores.T.T
is_identical = np.array_equal(scores, double_transpose)
print("\nDoes transposing twice give back the original matrix?", is_identical)

matrix_A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

matrix_B = np.array([
    [9, 10],
    [11, 12],
    [13, 14]
])

matrix_B_T = matrix_B.T
dot_product_result = np.dot(matrix_A, matrix_B_T)

print("\n=== Matrix A (4x2) ===\n", matrix_A)
print("\n=== Matrix B Transposed (2x3) ===\n", matrix_B_T)
print("\n=== Dot Product Result (4x3) ===\n", dot_product_result)

=== Original Scores Matrix (3x5) ===
 [[85 90 88 92 95]
 [70 75 80 78 85]
 [95 98 92 90 89]]

=== Transposed Scores Matrix (5x3) ===
 [[85 70 95]
 [90 75 98]
 [88 80 92]
 [92 78 90]
 [95 85 89]]
New Shape: (5, 3)

Does transposing twice give back the original matrix? True

=== Matrix A (4x2) ===
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

=== Matrix B Transposed (2x3) ===
 [[ 9 11 13]
 [10 12 14]]

=== Dot Product Result (4x3) ===
 [[ 29  35  41]
 [ 67  81  95]
 [105 127 149]
 [143 173 203]]
